[package]
name = "botoh"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
pretty_env_logger = "0.5.0"
reqwest = { version = "0.12.4", features = ["json"] }
sysinfo = "0.30.12"
tokio = { version = "1.37.0", features = ["full"] }
twitch-irc = "5.0.1"
